export const elementInfo = {
  label: "",
  css: {
    width: "",
    height: "",
  },
  attr: {
    placeholder: "",
    size: "",
    type: "",
    disabled: "",
    accept: "",
    alt: "",
    autoComplete: "",
    accessKey: "",
    autoCapitalize: "",
    className: "",
    dir: "",
    draggable: "",
    hidden: "",
    id: "",
    inputMode: "",
    itemID: "",
    itemProp: "",
    itemRef: "",
    itemScope: "",
    itemType: "",
    lang: "",
    part: "",
    slot: "",
    spellCheck: "",

    tabIndex: "",
    title: "",
    translate: "",
  },
  textareaAttr: {
    autoFocus: "",
    cols: "",
    dirname: "",
    disabled: "",
    readOnly: "",
    placeholder: "",
    wrap: "",
    required: "",
  },
};
